###

# Get Services

GET http://localhost:8001/services
Accept: application/json

###

# Get Service

GET http://localhost:8001/services/calcapi-service
Accept: application/json

###

# Get Routes

GET http://localhost:8001/routes
Accept: application/json

###

# Get Route

GET http://localhost:8001/services/calcapi-service/routes/calcapi-route
Accept: application/json

###

# A Simple Test
POST http://localhost:8000/api/Calculations/Add
Host: calcapi.com
Content-Type: application/json


{
    "number1": 17,
    "number2": 4
}

###

# Another Simple Test
POST http://localhost:8000/api/Calculations/Add
Host: unrestricted.calcapi.com
Content-Type: application/json
apikey: b8e6dd8a-64d4-41a1-9f8c-d70d63660d79


{
    "number1": 17,
    "number2": 4
}
