version: '3.7'

networks:
  kong-net:

services:

  calc-api:
    image: calcapi:latest
    networks:
      - kong-net
    ports:
      - 5001:80/tcp
    restart: on-failure
    build:
      context: ../../src/CalcApi
      dockerfile: Dockerfile

  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-root}"
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_PLUGINS: bundled,oidc,kong-spec-expose,kong-service-virtualization,kong-plugin-url-rewrite,kong-response-size-limiting,upstream-auth-basic
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    networks:
      - kong-net
    ports:
      - 8000:8000/tcp
      - 8001:8001/tcp
      - 8443:8443/tcp
      - 8444:8444/tcp
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

  konga:
    image: pantsel/konga:next
    restart: always
    networks:
        - kong-net
    environment:
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      NODE_ENV: production
    depends_on:
      - kong
    ports:
      - 1337:1337/tcp