_format_version: "1.1"

services:
- name: calcapi-service
  url: http://calc-api:80
  tags:
  - demo

routes:
- name: calcapi-route
  service: calcapi-service
  hosts: ["calcapi.com"]
  tags:
  - demo

# plugins:
# - name: ip-restriction
#   route: calcapi-route
#   config: 
#     whitelist: ["172.18.0.0/16"]
#     #whitelist: ["172.18.0.3"]
#   tags:
#   - demo
