# Postman Echo

# https://docs.postman-echo.com/

###

# Create a Service

POST http://localhost:8001/services
Content-Type: application/json

{
    "name": "postman-echo",
    "url": "https://postman-echo.com/"
}

###

# Create a Route

POST http://localhost:8001/services/postman-echo/routes
Content-Type: application/json

{
    "name" : "get-postman-echo-route",
    "hosts" : [
        "echo.com"
    ],
    "methods" : [
        "GET"
    ]
}

###

# Create another Route

POST http://localhost:8001/services/postman-echo/routes
Content-Type: application/json

{
    "name" : "post-postman-echo-route",
    "hosts" : [
        "echo.com"
    ],
    "methods" : [
        "POST"
    ]
}

###

# Create Upstream Auth Basic Plugin
POST http://localhost:8001/routes/post-postman-echo-route/plugins
Content-Type: application/json

{
    "name" : "upstream-auth-basic",
    "config" :
    {
        "username" : "johndoe",
        "password" : "s3cr3t!"
    }
}



###

# GET
GET http://localhost:8000/get?valid=false
Host: echo.com
Content-Type: application/json

###

# POST

POST http://localhost:8000/post
Host: echo.com
Content-Type: application/json

{
    "valid": false
}
