version: '2.1'

networks:
  kong-net:
services:
  calc-api:
    image: calc-api:latest
    networks:
      - kong-net
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5001:80/tcp
    restart: on-failure
    build:
      context: ../src/CalcSolution/Calc.Api
      dockerfile: Dockerfile
  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-root}"
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    networks:
      - kong-net
    ports:
      - 8000:8000/tcp
      - 8001:8001/tcp
      - 8443:8443/tcp
      - 8444:8444/tcp
    restart: on-failure
  konga:
    image: pantsel/konga:next
    restart: always
    networks:
        - kong-net
    environment:
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      NODE_ENV: production
    depends_on:
      - kong
    ports:
      - 1337:1337/tcp